INSERT INTO jatetxea_janariak (izena, prezioa, kopurua, argazkia, deskripzioa, janarimota, posizioa) VALUES 
('Durum', '6.99', '20', 'durum.png','Kebab haragia fajita batean bilduta, kalitate oneneko barazkiekin eta guk egindako saltsekin.', 1, 1), 
('Doner Kebab', '5.99', '20', 'kebab.png','Kebab haragia pita ogian bilduta, kalitate oneneko barazkiekin eta guk egindako saltsekin.', 1, 2),
('Pedrata', '3.50', '20', 'pedrata.png','Kebab haragia patatekin eta guk egindako saltsekin.', 1, 1),
('Lahmacun', '6.00', '20', 'lahmacum.png','Kebab haragia, kipula, peregil eta espeziekin labean egina.', 1, 2),
('Burger klasikoa', '8.50', '20', 'burgerclasica.png','Burger haragia, letxuga, tomatea eta maionesa.',2, 1),
('Burger berezia', '10.50', '20', 'burgercarne.png','Burger haragia, bacon, txedar gazta, saiheskia, kipula, tomatea eta letxuga.', 2, 2),
('Oilaskoa burger', '8.00', '20', 'burgerpollo.png','Oilasko haragia rebozatua, maionesa eta letxugarekin.', 2, 1),
('Burger bikoitza', '14.00', '20', 'burgerdoble.png','Bi burger haragi zati, txedar bikoitza, letxuga eta tomatea.', 2, 2),
('Margarita', '11.50', '20', 'margarita.png','Gazta, tomate eta oreganoa.', 3, 1),
('Bacon', '12.30', '20', 'pizzabacon.png','Bacon haragia, tomate eta gazta.', 3, 2),
('Barbakoa', '13.50', '20', 'pizzabarbacoa.png','Bacon, oilaskoa, kipula, barbakoa saltsa eta gazta.', 3, 1),
('Karbonara', '13.50', '20', 'carbonara.png','Perretxikoak, bacon, gazta, kipula, perejil eta baratxuria.', 3, 2),
('Triple haragi', '16.00', '20', 'pizzaharagi.png','Bacon, hanburgesa haragia, pepperoni, kipula, piperra eta gazta.', 3, 1),
('Kebab', '13.50', '20', 'kebabpizza.png','Kebab haragia, kipula, gazta eta tomatea.', 3, 2),
('Oilasko hegoak', '5.99', '20', 'alitas.png','Oilasko hegoak frijituak eta gure saltsa bereziarekin kondimentatuak.', 4, 1), 
('Kipula eraztunak', '4.99', '20', 'aroscebolla.png','Kipula eraztunak olio eta gatz kopuru onenarekin frijituak.', 4, 2),
('Nugget-ak', '5.00', '20', 'nuggets.png','Oilasko nugget frijituak, barbakoa saltsarekin.', 4, 1),
('Patata fijituak', '4.00', '20', 'patatas.png','Patata frijitu klasikoak, betikoak.', 4, 2),
('Deluxe patatak', '4.50', '20', 'deluxePatatas.png','Patata frijitu bereziak.', 4, 1);