INSERT INTO jatetxea_janari (izena, prezioa, kopurua, argazkia) VALUES 
('Durum', '6.99', '20', 'durum.png','Kebab haragia fajita batean bilduta, kalitate oneneko barazkiekin eta guk egindako saltsekin.'), 
('Doner Kebab', '5.99', '20', 'kebab.png','Kebab haragia pita ogian bilduta, kalitate oneneko barazkiekin eta guk egindako saltsekin.'),
('Pedrata', '3.50', '20', 'pedrata.png','Kebab haragia patatekin eta guk egindako saltsekin.'),
('Lahmacun', '6.00', '20', 'lahmacum.png','Kebab haragia, kipula, peregil eta espeziekin labean egina.'),
('Burger klasikoa', '8.50', '20', 'burgerclasica.png','Burger haragia, letxuga, tomatea eta maionesa.'),
('Burger berezia', '10.50', '20', 'burgercarne.png','Burger haragia, bacon, txedar gazta, saiheskia, kipula, tomatea eta letxuga.'),
('Oilaskoa burger', '8.00', '20', 'burgerpollo.png','Oilasko haragia rebozatua, maionesa eta letxugarekin.'),
('Burger bikoitza', '14.00', '20', 'burgerdoble.png','Bi burger haragi zati, txedar bikoitza, letxuga eta tomatea.'),
('Margarita', '11.50', '20', 'margarita.png','Gazta, tomate eta oreganoa.'),
('Bacon', '12.30', '20', 'pizzabacon.png','Bacon haragia, tomate eta gazta.'),
('Barbakoa', '13.50', '20', 'pizzabarbacoa.png','Bacon, oilaskoa, kipula, barbakoa saltsa eta gazta.'),
('Karbonara', '13.50', '20', 'carbonara.png','Perretxikoak, bacon, gazta, kipula, perejil eta baratxuria.'),
('Triple haragi', '16.00', '20', 'pizzaharagi.png','Bacon, hanburgesa haragia, pepperoni, kipula, piperra eta gazta.'),
('Kebab', '13.50', '20', 'kebabpizza.png','Kebab haragia, kipula, gazta eta tomatea.');