# Generated by Django 3.2.8 on 2021-10-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banatzailea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nanbanatzailea', models.CharField(max_length=9, verbose_name='NaNBanatzailea')),
                ('izena', models.CharField(max_length=50)),
                ('abizena', models.CharField(max_length=50)),
                ('telefonoa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Janariak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izena', models.CharField(max_length=50)),
                ('prezioa', models.CharField(max_length=50)),
                ('kopurua', models.CharField(max_length=50)),
                ('argazkia', models.ImageField(upload_to='')),
                ('deskripzioa', models.CharField(max_length=100)),
                ('janarimota', models.CharField(max_length=100)),
            ],
        ),
    ]
