# Generated by Django 3.2.8 on 2021-10-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jatetxea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Janarimota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izena', models.CharField(max_length=50)),
                ('argazkia', models.ImageField(upload_to='')),
            ],
        ),
    ]
