# Generated by Django 3.2.8 on 2021-10-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banatzailea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nanbanatzailea', models.CharField(max_length=9)),
                ('izena', models.CharField(max_length=50)),
                ('abizena', models.CharField(max_length=50)),
                ('telefonoa', models.CharField(max_length=50)),
            ],
        ),
    ]
